name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      force_destroy:
        description: 'Force destroy all resources'
        required: false
        default: false
        type: boolean

env:
  TERRAFORM_REPO : ${{ vars.TERRAFORM_REPO }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_TERRAFORM_BUCKET: ${{ vars.AWS_TERRAFORM_BUCKET }}
  AWS_CONTENT_BUCKET : ${{ vars.AWS_CONTENT_BUCKET }}
  TERRAFORM_VERSION : ${{ vars.TERRAFORM_VERSION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Terraform repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TERRAFORM_REPO }}
          token: ${{ secrets.PAT_PIPELINE }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init Backend
        working-directory: main
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_TERRAFORM_BUCKET: ${{ env.AWS_TERRAFORM_BUCKET }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_aws_terraform_bucket: ${{ env.AWS_TERRAFORM_BUCKET }}
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_content_bucket: ${{ env.AWS_CONTENT_BUCKET }}
        run: |
          terraform init \
            -backend-config="bucket=${AWS_TERRAFORM_BUCKET}" \
            -backend-config="key=${PROJECT_NAME}/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=terraform-locks"
      - name: Terraform Destroy
        working-directory: main
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_TERRAFORM_BUCKET: ${{ env.AWS_TERRAFORM_BUCKET }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_region: ${{ env.AWS_REGION }}
          TF_VAR_aws_terraform_bucket: ${{ env.AWS_TERRAFORM_BUCKET }}
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_content_bucket: ${{ env.AWS_CONTENT_BUCKET }}
        run: |
          if ${{ github.event.inputs.force_destroy }}; then
            terraform destroy -auto-approve -lock=false
          else
            terraform apply -auto-approve
          fi

